package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class Customer {
	
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.username
	 * @mbggenerated
	 */
	private String username;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.password
	 * @mbggenerated
	 */
	private String password;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.account_type
	 * @mbggenerated
	 */
	private Byte accountType;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.name
	 * @mbggenerated
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.city_id
	 * @mbggenerated
	 */
	private Integer cityId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.types
	 * @mbggenerated
	 */
	private Byte types;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.last_logined_at
	 * @mbggenerated
	 */
	private Date lastLoginedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.integral
	 * @mbggenerated
	 */
	private Integer integral;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.status
	 * @mbggenerated
	 */
	private Byte status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.device_code
	 * @mbggenerated
	 */
	private String deviceCode;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.phone
	 * @mbggenerated
	 */
	private String phone;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.email
	 * @mbggenerated
	 */
	private String email;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column customers.dentcode
	 * @mbggenerated
	 */
	private String dentcode;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.id
	 * @return  the value of customers.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.id
	 * @param id  the value for customers.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.username
	 * @return  the value of customers.username
	 * @mbggenerated
	 */
	public String getUsername() {
		return username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.username
	 * @param username  the value for customers.username
	 * @mbggenerated
	 */
	public void setUsername(String username) {
		this.username = username;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.password
	 * @return  the value of customers.password
	 * @mbggenerated
	 */
	public String getPassword() {
		return password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.password
	 * @param password  the value for customers.password
	 * @mbggenerated
	 */
	public void setPassword(String password) {
		this.password = password;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.account_type
	 * @return  the value of customers.account_type
	 * @mbggenerated
	 */
	public Byte getAccountType() {
		return accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.account_type
	 * @param accountType  the value for customers.account_type
	 * @mbggenerated
	 */
	public void setAccountType(Byte accountType) {
		this.accountType = accountType;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.name
	 * @return  the value of customers.name
	 * @mbggenerated
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.name
	 * @param name  the value for customers.name
	 * @mbggenerated
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.city_id
	 * @return  the value of customers.city_id
	 * @mbggenerated
	 */
	public Integer getCityId() {
		return cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.city_id
	 * @param cityId  the value for customers.city_id
	 * @mbggenerated
	 */
	public void setCityId(Integer cityId) {
		this.cityId = cityId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.types
	 * @return  the value of customers.types
	 * @mbggenerated
	 */
	public Byte getTypes() {
		return types;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.types
	 * @param types  the value for customers.types
	 * @mbggenerated
	 */
	public void setTypes(Byte types) {
		this.types = types;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.last_logined_at
	 * @return  the value of customers.last_logined_at
	 * @mbggenerated
	 */
	public Date getLastLoginedAt() {
		return lastLoginedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.last_logined_at
	 * @param lastLoginedAt  the value for customers.last_logined_at
	 * @mbggenerated
	 */
	public void setLastLoginedAt(Date lastLoginedAt) {
		this.lastLoginedAt = lastLoginedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.integral
	 * @return  the value of customers.integral
	 * @mbggenerated
	 */
	public Integer getIntegral() {
		return integral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.integral
	 * @param integral  the value for customers.integral
	 * @mbggenerated
	 */
	public void setIntegral(Integer integral) {
		this.integral = integral;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.status
	 * @return  the value of customers.status
	 * @mbggenerated
	 */
	public Byte getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.status
	 * @param status  the value for customers.status
	 * @mbggenerated
	 */
	public void setStatus(Byte status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.device_code
	 * @return  the value of customers.device_code
	 * @mbggenerated
	 */
	public String getDeviceCode() {
		return deviceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.device_code
	 * @param deviceCode  the value for customers.device_code
	 * @mbggenerated
	 */
	public void setDeviceCode(String deviceCode) {
		this.deviceCode = deviceCode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.created_at
	 * @return  the value of customers.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.created_at
	 * @param createdAt  the value for customers.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.updated_at
	 * @return  the value of customers.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.updated_at
	 * @param updatedAt  the value for customers.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.phone
	 * @return  the value of customers.phone
	 * @mbggenerated
	 */
	public String getPhone() {
		return phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.phone
	 * @param phone  the value for customers.phone
	 * @mbggenerated
	 */
	public void setPhone(String phone) {
		this.phone = phone;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.email
	 * @return  the value of customers.email
	 * @mbggenerated
	 */
	public String getEmail() {
		return email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.email
	 * @param email  the value for customers.email
	 * @mbggenerated
	 */
	public void setEmail(String email) {
		this.email = email;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column customers.dentcode
	 * @return  the value of customers.dentcode
	 * @mbggenerated
	 */
	public String getDentcode() {
		return dentcode;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column customers.dentcode
	 * @param dentcode  the value for customers.dentcode
	 * @mbggenerated
	 */
	public void setDentcode(String dentcode) {
		this.dentcode = dentcode;
	}

	/**
	 * 未激活
	 */
	public static final byte STATUS_NON_ACTIVE = 1;
	/**
	 * 正常
	 */
	public static final byte STATUS_NORMAL = 2;
	/**
	 * 停用
	 */
	public static final byte STATUS_STOP = 3;
	

	/**
	 * 普通用户/商户
	 */
	public static final byte TYPE_CUSTOMER = 1;
	/**
	 * 代理商
	 */
	public static final byte TYPE_AGENT = 2;
	/**
	 * 运营
	 */
	public static final byte TYPE_OPERATE = 3;
	/**
	 * 超级管理员
	 */
	public static final byte TYPE_SUPER = 4;
	/**
	 * 第三方机构
	 */
	public static final byte TYPE_THIRD_PARTY = 5;
	/**
	 * 代理商员工
	 */
	public static final byte TYPE_AGENT_STAFF = 6;

	/**
	 * 手机
	 */
	public static final byte ACCOUNT_TYPE_PHONE = 1;
	/**
	 * email
	 */
	public static final byte ACCOUNT_TYPE_EMAIL = 2;

    private City city;

    public City getCity() {
        return city;
    }

    public void setCity(City city) {
        this.city = city;
    }
}