package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class ExchangeGoodsRecord {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exchange_goods_records.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exchange_goods_records.customer_id
	 * @mbggenerated
	 */
	private Integer customerId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exchange_goods_records.from_agent_id
	 * @mbggenerated
	 */
	private Integer fromAgentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exchange_goods_records.to_agent_id
	 * @mbggenerated
	 */
	private Integer toAgentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exchange_goods_records.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exchange_goods_records.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exchange_goods_records.quantity
	 * @mbggenerated
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column exchange_goods_records.terminals_list
	 * @mbggenerated
	 */
	private String terminalsList;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exchange_goods_records.id
	 * @return  the value of exchange_goods_records.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exchange_goods_records.id
	 * @param id  the value for exchange_goods_records.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exchange_goods_records.customer_id
	 * @return  the value of exchange_goods_records.customer_id
	 * @mbggenerated
	 */
	public Integer getCustomerId() {
		return customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exchange_goods_records.customer_id
	 * @param customerId  the value for exchange_goods_records.customer_id
	 * @mbggenerated
	 */
	public void setCustomerId(Integer customerId) {
		this.customerId = customerId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exchange_goods_records.from_agent_id
	 * @return  the value of exchange_goods_records.from_agent_id
	 * @mbggenerated
	 */
	public Integer getFromAgentId() {
		return fromAgentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exchange_goods_records.from_agent_id
	 * @param fromAgentId  the value for exchange_goods_records.from_agent_id
	 * @mbggenerated
	 */
	public void setFromAgentId(Integer fromAgentId) {
		this.fromAgentId = fromAgentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exchange_goods_records.to_agent_id
	 * @return  the value of exchange_goods_records.to_agent_id
	 * @mbggenerated
	 */
	public Integer getToAgentId() {
		return toAgentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exchange_goods_records.to_agent_id
	 * @param toAgentId  the value for exchange_goods_records.to_agent_id
	 * @mbggenerated
	 */
	public void setToAgentId(Integer toAgentId) {
		this.toAgentId = toAgentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exchange_goods_records.created_at
	 * @return  the value of exchange_goods_records.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exchange_goods_records.created_at
	 * @param createdAt  the value for exchange_goods_records.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exchange_goods_records.updated_at
	 * @return  the value of exchange_goods_records.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exchange_goods_records.updated_at
	 * @param updatedAt  the value for exchange_goods_records.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exchange_goods_records.quantity
	 * @return  the value of exchange_goods_records.quantity
	 * @mbggenerated
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exchange_goods_records.quantity
	 * @param quantity  the value for exchange_goods_records.quantity
	 * @mbggenerated
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column exchange_goods_records.terminals_list
	 * @return  the value of exchange_goods_records.terminals_list
	 * @mbggenerated
	 */
	public String getTerminalsList() {
		return terminalsList;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column exchange_goods_records.terminals_list
	 * @param terminalsList  the value for exchange_goods_records.terminals_list
	 * @mbggenerated
	 */
	public void setTerminalsList(String terminalsList) {
		this.terminalsList = terminalsList;
	}
}