package com.comdosoft.financial.manage.domain.zhangfu;

import java.util.Date;

public class OrderGood {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.pay_channel_id
	 * @mbggenerated
	 */
	private Integer payChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.quantity
	 * @mbggenerated
	 */
	private Integer quantity;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.price
	 * @mbggenerated
	 */
	private Integer price;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.actual_price
	 * @mbggenerated
	 */
	private Integer actualPrice;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.order_id
	 * @mbggenerated
	 */
	private Integer orderId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.created_at
	 * @mbggenerated
	 */
	private Date createdAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.updated_at
	 * @mbggenerated
	 */
	private Date updatedAt;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column order_goods.good_id
	 * @mbggenerated
	 */
	private Integer goodId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.id
	 * @return  the value of order_goods.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.id
	 * @param id  the value for order_goods.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.pay_channel_id
	 * @return  the value of order_goods.pay_channel_id
	 * @mbggenerated
	 */
	public Integer getPayChannelId() {
		return payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.pay_channel_id
	 * @param payChannelId  the value for order_goods.pay_channel_id
	 * @mbggenerated
	 */
	public void setPayChannelId(Integer payChannelId) {
		this.payChannelId = payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.quantity
	 * @return  the value of order_goods.quantity
	 * @mbggenerated
	 */
	public Integer getQuantity() {
		return quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.quantity
	 * @param quantity  the value for order_goods.quantity
	 * @mbggenerated
	 */
	public void setQuantity(Integer quantity) {
		this.quantity = quantity;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.price
	 * @return  the value of order_goods.price
	 * @mbggenerated
	 */
	public Integer getPrice() {
		return price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.price
	 * @param price  the value for order_goods.price
	 * @mbggenerated
	 */
	public void setPrice(Integer price) {
		this.price = price;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.actual_price
	 * @return  the value of order_goods.actual_price
	 * @mbggenerated
	 */
	public Integer getActualPrice() {
		return actualPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.actual_price
	 * @param actualPrice  the value for order_goods.actual_price
	 * @mbggenerated
	 */
	public void setActualPrice(Integer actualPrice) {
		this.actualPrice = actualPrice;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.order_id
	 * @return  the value of order_goods.order_id
	 * @mbggenerated
	 */
	public Integer getOrderId() {
		return orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.order_id
	 * @param orderId  the value for order_goods.order_id
	 * @mbggenerated
	 */
	public void setOrderId(Integer orderId) {
		this.orderId = orderId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.created_at
	 * @return  the value of order_goods.created_at
	 * @mbggenerated
	 */
	public Date getCreatedAt() {
		return createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.created_at
	 * @param createdAt  the value for order_goods.created_at
	 * @mbggenerated
	 */
	public void setCreatedAt(Date createdAt) {
		this.createdAt = createdAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.updated_at
	 * @return  the value of order_goods.updated_at
	 * @mbggenerated
	 */
	public Date getUpdatedAt() {
		return updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.updated_at
	 * @param updatedAt  the value for order_goods.updated_at
	 * @mbggenerated
	 */
	public void setUpdatedAt(Date updatedAt) {
		this.updatedAt = updatedAt;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column order_goods.good_id
	 * @return  the value of order_goods.good_id
	 * @mbggenerated
	 */
	public Integer getGoodId() {
		return goodId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column order_goods.good_id
	 * @param goodId  the value for order_goods.good_id
	 * @mbggenerated
	 */
	public void setGoodId(Integer goodId) {
		this.goodId = goodId;
	}
	
	private Good good;
	private GoodBrand goodBrand;
	private PayChannel payChannel;

	public Good getGood() {
		return good;
	}

	public void setGood(Good good) {
		this.good = good;
	}

	public GoodBrand getGoodBrand() {
		return goodBrand;
	}

	public void setGoodBrand(GoodBrand goodBrand) {
		this.goodBrand = goodBrand;
	}

	public PayChannel getPayChannel() {
		return payChannel;
	}

	public void setPayChannel(PayChannel payChannel) {
		this.payChannel = payChannel;
	}
}