package com.comdosoft.financial.manage.domain.zhangfu;

public class PayChannelBillingCycle {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_channel_billing_cycles.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_channel_billing_cycles.pay_channel_id
	 * @mbggenerated
	 */
	private Integer payChannelId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_channel_billing_cycles.billing_cycles_id
	 * @mbggenerated
	 */
	private Integer billingCyclesId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_channel_billing_cycles.description
	 * @mbggenerated
	 */
	private String description;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column pay_channel_billing_cycles.rate
	 * @mbggenerated
	 */
	private Integer rate;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_channel_billing_cycles.id
	 * @return  the value of pay_channel_billing_cycles.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_channel_billing_cycles.id
	 * @param id  the value for pay_channel_billing_cycles.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_channel_billing_cycles.pay_channel_id
	 * @return  the value of pay_channel_billing_cycles.pay_channel_id
	 * @mbggenerated
	 */
	public Integer getPayChannelId() {
		return payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_channel_billing_cycles.pay_channel_id
	 * @param payChannelId  the value for pay_channel_billing_cycles.pay_channel_id
	 * @mbggenerated
	 */
	public void setPayChannelId(Integer payChannelId) {
		this.payChannelId = payChannelId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_channel_billing_cycles.billing_cycles_id
	 * @return  the value of pay_channel_billing_cycles.billing_cycles_id
	 * @mbggenerated
	 */
	public Integer getBillingCyclesId() {
		return billingCyclesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_channel_billing_cycles.billing_cycles_id
	 * @param billingCyclesId  the value for pay_channel_billing_cycles.billing_cycles_id
	 * @mbggenerated
	 */
	public void setBillingCyclesId(Integer billingCyclesId) {
		this.billingCyclesId = billingCyclesId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_channel_billing_cycles.description
	 * @return  the value of pay_channel_billing_cycles.description
	 * @mbggenerated
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_channel_billing_cycles.description
	 * @param description  the value for pay_channel_billing_cycles.description
	 * @mbggenerated
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column pay_channel_billing_cycles.rate
	 * @return  the value of pay_channel_billing_cycles.rate
	 * @mbggenerated
	 */
	public Integer getRate() {
		return rate;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column pay_channel_billing_cycles.rate
	 * @param rate  the value for pay_channel_billing_cycles.rate
	 * @mbggenerated
	 */
	public void setRate(Integer rate) {
		this.rate = rate;
	}

	private DictionaryBillingCycle dictionaryBillingCycle;

	public DictionaryBillingCycle getDictionaryBillingCycle() {
		return dictionaryBillingCycle;
	}

	public void setDictionaryBillingCycle(DictionaryBillingCycle dictionaryBillingCycle) {
		this.dictionaryBillingCycle = dictionaryBillingCycle;
	}
}