package com.comdosoft.financial.manage.domain.zhangfu;

public class RoleMenu {

	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_menus.id
	 * @mbggenerated
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_menus.role_id
	 * @mbggenerated
	 */
	private Integer roleId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column role_menus.menu_id
	 * @mbggenerated
	 */
	private Integer menuId;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_menus.id
	 * @return  the value of role_menus.id
	 * @mbggenerated
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_menus.id
	 * @param id  the value for role_menus.id
	 * @mbggenerated
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_menus.role_id
	 * @return  the value of role_menus.role_id
	 * @mbggenerated
	 */
	public Integer getRoleId() {
		return roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_menus.role_id
	 * @param roleId  the value for role_menus.role_id
	 * @mbggenerated
	 */
	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column role_menus.menu_id
	 * @return  the value of role_menus.menu_id
	 * @mbggenerated
	 */
	public Integer getMenuId() {
		return menuId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column role_menus.menu_id
	 * @param menuId  the value for role_menus.menu_id
	 * @mbggenerated
	 */
	public void setMenuId(Integer menuId) {
		this.menuId = menuId;
	}
}