package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.AgentProfitSetting;
import java.util.List;

public interface AgentProfitSettingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	int insert(AgentProfitSetting record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	AgentProfitSetting selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	List<AgentProfitSetting> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AgentProfitSetting record);

	List<AgentProfitSetting> selectAgentProfitSettings(Integer agentId);

	void deleteByAgentIdAndChannelId(Integer agentId, Integer channelId);
}