package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsAgent;
import java.util.List;

public interface CsAgentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_agents
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_agents
	 * @mbggenerated
	 */
	int insert(CsAgent record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_agents
	 * @mbggenerated
	 */
	CsAgent selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_agents
	 * @mbggenerated
	 */
	List<CsAgent> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_agents
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsAgent record);
}