package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsCancel;
import java.util.List;

public interface CsCancelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	int insert(CsCancel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	CsCancel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	List<CsCancel> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_cancels
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsCancel record);
}