package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsChange;
import java.util.List;

public interface CsChangeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_changes
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_changes
	 * @mbggenerated
	 */
	int insert(CsChange record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_changes
	 * @mbggenerated
	 */
	CsChange selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_changes
	 * @mbggenerated
	 */
	List<CsChange> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_changes
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsChange record);
}