package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsLeaseReturn;
import java.util.List;

public interface CsLeaseReturnMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_returns
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_returns
	 * @mbggenerated
	 */
	int insert(CsLeaseReturn record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_returns
	 * @mbggenerated
	 */
	CsLeaseReturn selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_returns
	 * @mbggenerated
	 */
	List<CsLeaseReturn> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_returns
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsLeaseReturn record);
}