package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsLeaseReturnMark;
import java.util.List;

public interface CsLeaseReturnMarkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	int insert(CsLeaseReturnMark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	CsLeaseReturnMark selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	List<CsLeaseReturnMark> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_lease_return_marks
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsLeaseReturnMark record);
}