package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsOutStorage;
import java.util.List;

public interface CsOutStorageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_out_storages
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_out_storages
	 * @mbggenerated
	 */
	int insert(CsOutStorage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_out_storages
	 * @mbggenerated
	 */
	CsOutStorage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_out_storages
	 * @mbggenerated
	 */
	List<CsOutStorage> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_out_storages
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsOutStorage record);
}