package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsRepairPayment;
import java.util.List;

public interface CsRepairPaymentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repair_payments
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repair_payments
	 * @mbggenerated
	 */
	int insert(CsRepairPayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repair_payments
	 * @mbggenerated
	 */
	CsRepairPayment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repair_payments
	 * @mbggenerated
	 */
	List<CsRepairPayment> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_repair_payments
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsRepairPayment record);
}