package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsReturnMark;
import java.util.List;

public interface CsReturnMarkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_return_marks
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_return_marks
	 * @mbggenerated
	 */
	int insert(CsReturnMark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_return_marks
	 * @mbggenerated
	 */
	CsReturnMark selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_return_marks
	 * @mbggenerated
	 */
	List<CsReturnMark> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_return_marks
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsReturnMark record);
}