package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsRefundMark;
import java.util.List;

public interface CsRefundMarkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refund_marks
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refund_marks
	 * @mbggenerated
	 */
	int insert(CsRefundMark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refund_marks
	 * @mbggenerated
	 */
	CsRefundMark selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refund_marks
	 * @mbggenerated
	 */
	List<CsRefundMark> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refund_marks
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsRefundMark record);
}