package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsRefund;
import java.util.List;

public interface CsRefundMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refunds
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refunds
	 * @mbggenerated
	 */
	int insert(CsRefund record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refunds
	 * @mbggenerated
	 */
	CsRefund selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refunds
	 * @mbggenerated
	 */
	List<CsRefund> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_refunds
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsRefund record);
}