package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CsUpdateInfo;
import java.util.List;

public interface CsUpdateInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_update_infos
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_update_infos
	 * @mbggenerated
	 */
	int insert(CsUpdateInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_update_infos
	 * @mbggenerated
	 */
	CsUpdateInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_update_infos
	 * @mbggenerated
	 */
	List<CsUpdateInfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cs_update_infos
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CsUpdateInfo record);
}