package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CustomerIntegralRecord;
import java.util.List;

public interface CustomerIntegralRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_records
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_records
	 * @mbggenerated
	 */
	int insert(CustomerIntegralRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_records
	 * @mbggenerated
	 */
	CustomerIntegralRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_records
	 * @mbggenerated
	 */
	List<CustomerIntegralRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_records
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CustomerIntegralRecord record);
}