package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CustomerRoleRelation;
import java.util.List;

public interface CustomerRoleRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_role_relations
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_role_relations
	 * @mbggenerated
	 */
	int insert(CustomerRoleRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_role_relations
	 * @mbggenerated
	 */
	CustomerRoleRelation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_role_relations
	 * @mbggenerated
	 */
	List<CustomerRoleRelation> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_role_relations
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CustomerRoleRelation record);

	int deleteByCustomerId(Integer customerId);
}