package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.Agent;
import com.comdosoft.financial.manage.domain.zhangfu.CustomerAgentRelation;
import com.comdosoft.financial.manage.utils.page.PageRequest;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface CustomerAgentRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_agent_relations
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_agent_relations
	 * @mbggenerated
	 */
	int insert(CustomerAgentRelation record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_agent_relations
	 * @mbggenerated
	 */
	CustomerAgentRelation selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_agent_relations
	 * @mbggenerated
	 */
	List<CustomerAgentRelation> selectAll();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_agent_relations
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CustomerAgentRelation record);
	List<Agent> customerAgents(Integer customerId,PageRequest request);
	long countCustomerAgents(@Param("customerId") Integer customerId);
}