package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CustomerIntention;
import java.util.List;

public interface CustomerIntentionMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_intentions
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_intentions
	 * @mbggenerated
	 */
	int insert(CustomerIntention record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_intentions
	 * @mbggenerated
	 */
	CustomerIntention selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_intentions
	 * @mbggenerated
	 */
	List<CustomerIntention> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_intentions
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CustomerIntention record);
}