package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CustomerIntegralConvert;
import java.util.List;

public interface CustomerIntegralConvertMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	int insert(CustomerIntegralConvert record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	CustomerIntegralConvert selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	List<CustomerIntegralConvert> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_integral_converts
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CustomerIntegralConvert record);
}