package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.CustomerAddress;
import java.util.List;

public interface CustomerAddressMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_addresses
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_addresses
	 * @mbggenerated
	 */
	int insert(CustomerAddress record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_addresses
	 * @mbggenerated
	 */
	CustomerAddress selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_addresses
	 * @mbggenerated
	 */
	List<CustomerAddress> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table customer_addresses
	 * @mbggenerated
	 */
	int updateByPrimaryKey(CustomerAddress record);
	
	List<CustomerAddress> selectCustomerAddress(Integer customerId);
}