package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DangerMerchant;
import java.util.List;

public interface DangerMerchantMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table danger_merchants
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table danger_merchants
	 * @mbggenerated
	 */
	int insert(DangerMerchant record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table danger_merchants
	 * @mbggenerated
	 */
	DangerMerchant selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table danger_merchants
	 * @mbggenerated
	 */
	List<DangerMerchant> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table danger_merchants
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DangerMerchant record);
}