package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionaryTradeType;
import java.util.List;

public interface DictionaryTradeTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_types
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_types
	 * @mbggenerated
	 */
	int insert(DictionaryTradeType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_types
	 * @mbggenerated
	 */
	DictionaryTradeType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_types
	 * @mbggenerated
	 */
	List<DictionaryTradeType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_types
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DictionaryTradeType record);

	DictionaryTradeType selectBaseTradeType();
}