package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionarySignOrderWay;
import java.util.List;

public interface DictionarySignOrderWayMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_sign_order_ways
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_sign_order_ways
	 * @mbggenerated
	 */
	int insert(DictionarySignOrderWay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_sign_order_ways
	 * @mbggenerated
	 */
	DictionarySignOrderWay selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_sign_order_ways
	 * @mbggenerated
	 */
	List<DictionarySignOrderWay> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_sign_order_ways
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DictionarySignOrderWay record);
}