package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionaryCardType;
import java.util.List;

public interface DictionaryCardTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_card_types
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_card_types
	 * @mbggenerated
	 */
	int insert(DictionaryCardType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_card_types
	 * @mbggenerated
	 */
	DictionaryCardType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_card_types
	 * @mbggenerated
	 */
	List<DictionaryCardType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_card_types
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DictionaryCardType record);

	List<DictionaryCardType> selectCardTypes(Integer goodId);
}