package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionaryEncryptCardWay;
import java.util.List;

public interface DictionaryEncryptCardWayMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_encrypt_card_ways
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_encrypt_card_ways
	 * @mbggenerated
	 */
	int insert(DictionaryEncryptCardWay record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_encrypt_card_ways
	 * @mbggenerated
	 */
	DictionaryEncryptCardWay selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_encrypt_card_ways
	 * @mbggenerated
	 */
	List<DictionaryEncryptCardWay> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_encrypt_card_ways
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DictionaryEncryptCardWay record);
}