package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionaryTradeStandardRate;
import java.util.List;

public interface DictionaryTradeStandardRateMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_standard_rates
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_standard_rates
	 * @mbggenerated
	 */
	int insert(DictionaryTradeStandardRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_standard_rates
	 * @mbggenerated
	 */
	DictionaryTradeStandardRate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_standard_rates
	 * @mbggenerated
	 */
	List<DictionaryTradeStandardRate> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_trade_standard_rates
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DictionaryTradeStandardRate record);
}