package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.DictionaryCreditType;
import java.util.List;

public interface DictionaryCreditTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_credit_types
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_credit_types
	 * @mbggenerated
	 */
	int insert(DictionaryCreditType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_credit_types
	 * @mbggenerated
	 */
	DictionaryCreditType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_credit_types
	 * @mbggenerated
	 */
	List<DictionaryCreditType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_credit_types
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DictionaryCreditType record);
}