package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.GoodBrand;
import java.util.List;

public interface GoodBrandMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_brands
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_brands
	 * @mbggenerated
	 */
	int insert(GoodBrand record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_brands
	 * @mbggenerated
	 */
	GoodBrand selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_brands
	 * @mbggenerated
	 */
	List<GoodBrand> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_brands
	 * @mbggenerated
	 */
	int updateByPrimaryKey(GoodBrand record);

	List<GoodBrand> selectByName(String name);

}