package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.GoodRelation;
import java.util.List;

public interface GoodRelationMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_relations
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_relations
	 * @mbggenerated
	 */
	int insert(GoodRelation record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_relations
	 * @mbggenerated
	 */
	GoodRelation selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_relations
	 * @mbggenerated
	 */
	List<GoodRelation> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_relations
	 * @mbggenerated
	 */
	int updateByPrimaryKey(GoodRelation record);

	void deleteByGoodId(Integer goodId);
}