package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.GoodMark;
import java.util.List;

public interface GoodMarkMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_marks
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_marks
	 * @mbggenerated
	 */
	int insert(GoodMark record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_marks
	 * @mbggenerated
	 */
	GoodMark selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_marks
	 * @mbggenerated
	 */
	List<GoodMark> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_marks
	 * @mbggenerated
	 */
	int updateByPrimaryKey(GoodMark record);
}