package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.InOutStorage;
import java.util.List;

public interface InOutStorageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table in_out_storages
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table in_out_storages
	 * @mbggenerated
	 */
	int insert(InOutStorage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table in_out_storages
	 * @mbggenerated
	 */
	InOutStorage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table in_out_storages
	 * @mbggenerated
	 */
	List<InOutStorage> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table in_out_storages
	 * @mbggenerated
	 */
	int updateByPrimaryKey(InOutStorage record);
}