package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.MessageReceiver;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface MessageReceiverMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_receivers
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_receivers
	 * @mbggenerated
	 */
	int insert(MessageReceiver record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_receivers
	 * @mbggenerated
	 */
	MessageReceiver selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_receivers
	 * @mbggenerated
	 */
	List<MessageReceiver> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table message_receivers
	 * @mbggenerated
	 */
	int updateByPrimaryKey(MessageReceiver record);

    void deleteBySysMessageId(Integer sysMessageId);

    void insertMessages( @Param("sysMessageId")Integer sysMessageId, @Param("goodId")Integer goodId, @Param("channelId")Integer channelId, @Param("customerType")Byte customerType);
}