package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.OpeningRequirementList;
import java.util.List;

public interface OpeningRequirementListMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_requirement_lists
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_requirement_lists
	 * @mbggenerated
	 */
	int insert(OpeningRequirementList record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_requirement_lists
	 * @mbggenerated
	 */
	OpeningRequirementList selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_requirement_lists
	 * @mbggenerated
	 */
	List<OpeningRequirementList> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_requirement_lists
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OpeningRequirementList record);

	List<OpeningRequirementList> selectPublicRequirements(Integer openingRequirementId);

	List<OpeningRequirementList> selectPrivateRequirements(Integer openingRequirementId);

    void deleteOpeningRequirementLists(Integer openingRequirementId);
}