package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.OpeningApplie;
import java.util.List;

public interface OpeningApplieMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	int insert(OpeningApplie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	OpeningApplie selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	List<OpeningApplie> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OpeningApplie record);

	OpeningApplie selectOpeningApplie(Integer terminalId);
}