package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.OrderPayment;
import java.util.List;

public interface OrderPaymentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_payments
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_payments
	 * @mbggenerated
	 */
	int insert(OrderPayment record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_payments
	 * @mbggenerated
	 */
	OrderPayment selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_payments
	 * @mbggenerated
	 */
	List<OrderPayment> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_payments
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OrderPayment record);
	
	List<OrderPayment> selectOrderPaymentsByOrderId(Integer orderId);
}