package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.OrderTradeRecord;
import java.util.List;

public interface OrderTradeRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_trade_records
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_trade_records
	 * @mbggenerated
	 */
	int insert(OrderTradeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_trade_records
	 * @mbggenerated
	 */
	OrderTradeRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_trade_records
	 * @mbggenerated
	 */
	List<OrderTradeRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table order_trade_records
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OrderTradeRecord record);
}