package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.PayChannelBillingCycle;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface PayChannelBillingCycleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_billing_cycles
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_billing_cycles
	 * @mbggenerated
	 */
	int insert(PayChannelBillingCycle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_billing_cycles
	 * @mbggenerated
	 */
	PayChannelBillingCycle selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_billing_cycles
	 * @mbggenerated
	 */
	List<PayChannelBillingCycle> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_billing_cycles
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PayChannelBillingCycle record);

	PayChannelBillingCycle findById(Integer id);

	List<PayChannelBillingCycle> selectBillingCycles(Integer payChannelId);

    void deletePayChannelBillingCycles(Integer payChannelId);

    PayChannelBillingCycle findByChannelIdAndBillingCyclesId(@Param("payChannelId")Integer channelId, @Param("billingCycleId")Integer billingCycleId);

}