package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.PayChannelStandardRate;
import java.util.List;

public interface PayChannelStandardRateMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_standard_rates
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_standard_rates
	 * @mbggenerated
	 */
	int insert(PayChannelStandardRate record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_standard_rates
	 * @mbggenerated
	 */
	PayChannelStandardRate selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_standard_rates
	 * @mbggenerated
	 */
	List<PayChannelStandardRate> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channel_standard_rates
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PayChannelStandardRate record);

	List<PayChannelStandardRate> selectStandardRates(Integer channelId);

    void deletePayChannelStandardRates(Integer channelId);
}