package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.PrepareGoodRecord;
import java.util.List;

public interface PrepareGoodRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prepare_goods_records
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prepare_goods_records
	 * @mbggenerated
	 */
	int insert(PrepareGoodRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prepare_goods_records
	 * @mbggenerated
	 */
	PrepareGoodRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prepare_goods_records
	 * @mbggenerated
	 */
	List<PrepareGoodRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table prepare_goods_records
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PrepareGoodRecord record);
}