package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.Role;
import com.comdosoft.financial.manage.utils.page.PageRequest;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated
	 */
	int insert(Role record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated
	 */
	Role selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated
	 */
	List<Role> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table roles
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Role record);

	List<Role> selectPage(@Param("request") PageRequest request,@Param("query") String query);
	
	long countTotal(@Param("query") String query);

    List<Role> customerRoles(Integer customerId);
}