package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.RoleMenu;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface RoleMenuMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menus
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menus
	 * @mbggenerated
	 */
	int insert(RoleMenu record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menus
	 * @mbggenerated
	 */
	RoleMenu selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menus
	 * @mbggenerated
	 */
	List<RoleMenu> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table role_menus
	 * @mbggenerated
	 */
	int updateByPrimaryKey(RoleMenu record);

	List<String> selectRoleKeys(@Param("roleId") Integer roleId);
	
	int deleteByRoleId(Integer roleId);
}