package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.ShoppingCart;
import java.util.List;

public interface ShoppingCartMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_carts
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_carts
	 * @mbggenerated
	 */
	int insert(ShoppingCart record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_carts
	 * @mbggenerated
	 */
	ShoppingCart selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_carts
	 * @mbggenerated
	 */
	List<ShoppingCart> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table shopping_carts
	 * @mbggenerated
	 */
	int updateByPrimaryKey(ShoppingCart record);
}