package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.SysMessage;
import com.comdosoft.financial.manage.utils.page.PageRequest;
import org.apache.ibatis.annotations.Param;

import java.util.List;

public interface SysMessageMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_messages
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_messages
	 * @mbggenerated
	 */
	int insert(SysMessage record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_messages
	 * @mbggenerated
	 */
	SysMessage selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_messages
	 * @mbggenerated
	 */
	List<SysMessage> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_messages
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysMessage record);

    long count();

    List<SysMessage> findPageMessages(@Param("pageRequest") PageRequest pageRequest);

}