package com.comdosoft.financial.manage.mapper.zhangfu;

import com.comdosoft.financial.manage.domain.zhangfu.TerminalTradeTypeInfo;
import java.util.List;

public interface TerminalTradeTypeInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	int insert(TerminalTradeTypeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	TerminalTradeTypeInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	List<TerminalTradeTypeInfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TerminalTradeTypeInfo record);

	List<TerminalTradeTypeInfo> selectTerminalTradeTypeInfos(Integer terminalId);
}