package com.comdosoft.financial.timing.mapper.trades;

import java.util.List;

import com.comdosoft.financial.timing.domain.trades.Profit;

public interface ProfitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profits
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profits
	 * @mbggenerated
	 */
	int insert(Profit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profits
	 * @mbggenerated
	 */
	Profit selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profits
	 * @mbggenerated
	 */
	List<Profit> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table profits
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Profit record);

}