package com.comdosoft.financial.timing.mapper.trades;

import java.util.List;

import com.comdosoft.financial.timing.domain.trades.TradeTransferRepaymentRecord;

public interface TradeTransferRepaymentRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_transfer_repayment_records
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_transfer_repayment_records
	 * @mbggenerated
	 */
	int insert(TradeTransferRepaymentRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_transfer_repayment_records
	 * @mbggenerated
	 */
	TradeTransferRepaymentRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_transfer_repayment_records
	 * @mbggenerated
	 */
	List<TradeTransferRepaymentRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_transfer_repayment_records
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TradeTransferRepaymentRecord record);
}