package com.comdosoft.financial.timing.mapper.trades;

import java.util.List;

import org.apache.ibatis.annotations.Param;

import com.comdosoft.financial.timing.domain.trades.TradeRecord;
import com.comdosoft.financial.timing.utils.page.PageRequest;

public interface TradeRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	int insert(TradeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	TradeRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	List<TradeRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TradeRecord record);

	List<TradeRecord> selectPage(@Param("request") PageRequest request,
								 @Param("attach") Integer attach,
                                 @Param("status") Integer status);

}