package com.comdosoft.financial.timing.mapper.trades;

import java.util.List;

import com.comdosoft.financial.timing.domain.trades.TradeRechargeRecord;

public interface TradeRechargeRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_recharge_records
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_recharge_records
	 * @mbggenerated
	 */
	int insert(TradeRechargeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_recharge_records
	 * @mbggenerated
	 */
	TradeRechargeRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_recharge_records
	 * @mbggenerated
	 */
	List<TradeRechargeRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_recharge_records
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TradeRechargeRecord record);
}