package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.AgentProfitSetting;

public interface AgentProfitSettingMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	int insert(AgentProfitSetting record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	AgentProfitSetting selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	List<AgentProfitSetting> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agent_profit_settings
	 * @mbggenerated
	 */
	int updateByPrimaryKey(AgentProfitSetting record);

	AgentProfitSetting selectBestProfitSetting(Integer agentId,
			Integer payChannelId,Integer tradeTypeId,Integer amount);
}