package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.Agent;

public interface AgentMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agents
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agents
	 * @mbggenerated
	 */
	int insert(Agent record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agents
	 * @mbggenerated
	 */
	Agent selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agents
	 * @mbggenerated
	 */
	List<Agent> selectAll();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table agents
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Agent record);

	Agent selectByCode(String code);
	
	List<Integer> getAllAgentsByTopAgent(String topAgentCode);
}