package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.City;

public interface CityMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cities
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cities
	 * @mbggenerated
	 */
	int insert(City record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cities
	 * @mbggenerated
	 */
	City selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cities
	 * @mbggenerated
	 */
	List<City> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table cities
	 * @mbggenerated
	 */
	int updateByPrimaryKey(City record);

}