package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.DictionaryBillingCycle;

public interface DictionaryBillingCycleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_billing_cycles
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_billing_cycles
	 * @mbggenerated
	 */
	int insert(DictionaryBillingCycle record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_billing_cycles
	 * @mbggenerated
	 */
	DictionaryBillingCycle selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_billing_cycles
	 * @mbggenerated
	 */
	List<DictionaryBillingCycle> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table dictionary_billing_cycles
	 * @mbggenerated
	 */
	int updateByPrimaryKey(DictionaryBillingCycle record);
}