package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.Merchant;
import com.comdosoft.financial.timing.utils.page.PageRequest;

public interface MerchantMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchants
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchants
	 * @mbggenerated
	 */
	int insert(Merchant record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchants
	 * @mbggenerated
	 */
	Merchant selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchants
	 * @mbggenerated
	 */
	List<Merchant> selectAll();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table merchants
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Merchant record);
	
	List<Merchant> selectByCustomerId(Integer customerId,PageRequest request);
	long countByCustomerId(Integer customerId);
}