package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.OpeningApplie;
import com.comdosoft.financial.timing.utils.page.PageRequest;

public interface OpeningApplieMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	int insert(OpeningApplie record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	OpeningApplie selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	List<OpeningApplie> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table opening_applies
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OpeningApplie record);
	
	OpeningApplie selectOpeningApplie(Integer terminalId);
	
	List<OpeningApplie> selectWithStatus(byte status,PageRequest request);
}