package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.OperateRecord;

public interface OperateRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operate_records
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operate_records
	 * @mbggenerated
	 */
	int insert(OperateRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operate_records
	 * @mbggenerated
	 */
	OperateRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operate_records
	 * @mbggenerated
	 */
	List<OperateRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table operate_records
	 * @mbggenerated
	 */
	int updateByPrimaryKey(OperateRecord record);
}