package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.PayChannel;

public interface PayChannelMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channels
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channels
	 * @mbggenerated
	 */
	int insert(PayChannel record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channels
	 * @mbggenerated
	 */
	PayChannel selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channels
	 * @mbggenerated
	 */
	List<PayChannel> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table pay_channels
	 * @mbggenerated
	 */
	int updateByPrimaryKey(PayChannel record);

}