package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.SupportTradeType;

public interface SupportTradeTypeMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table support_trade_types
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table support_trade_types
	 * @mbggenerated
	 */
	int insert(SupportTradeType record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table support_trade_types
	 * @mbggenerated
	 */
	SupportTradeType selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table support_trade_types
	 * @mbggenerated
	 */
	List<SupportTradeType> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table support_trade_types
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SupportTradeType record);

    SupportTradeType selectBaseSupportTradeType(Integer channelId,Integer tradeTypeId);

}