package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.SysConfig;

public interface SysConfigMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbggenerated
	 */
	int insert(SysConfig record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbggenerated
	 */
	SysConfig selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbggenerated
	 */
	List<SysConfig> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_config
	 * @mbggenerated
	 */
	int updateByPrimaryKey(SysConfig record);

    SysConfig findByKey(String key);
}