package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.TerminalOpeningInfo;

public interface TerminalOpeningInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_opening_infos
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_opening_infos
	 * @mbggenerated
	 */
	int insert(TerminalOpeningInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_opening_infos
	 * @mbggenerated
	 */
	TerminalOpeningInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_opening_infos
	 * @mbggenerated
	 */
	List<TerminalOpeningInfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_opening_infos
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TerminalOpeningInfo record);

	List<TerminalOpeningInfo> selectTerminalOpeningInfos(Integer openingAppliesId);
}