package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.Terminal;

public interface TerminalMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminals
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminals
	 * @mbggenerated
	 */
	int insert(Terminal record);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminals
	 * @mbggenerated
	 */
	Terminal selectByPrimaryKey(Integer id);
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminals
	 * @mbggenerated
	 */
	List<Terminal> selectAll();
	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminals
	 * @mbggenerated
	 */
	int updateByPrimaryKey(Terminal record);
	
	
	Terminal selectBySerial(String serial);

}
