package com.comdosoft.financial.timing.mapper.zhangfu;

import java.util.List;

import com.comdosoft.financial.timing.domain.zhangfu.TerminalTradeTypeInfo;

public interface TerminalTradeTypeInfoMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	int insert(TerminalTradeTypeInfo record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	TerminalTradeTypeInfo selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	List<TerminalTradeTypeInfo> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table terminal_trade_type_infos
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TerminalTradeTypeInfo record);

	int updateStatus(Integer status, Integer terminalId, Integer tradeTypeId);
	
	List<TerminalTradeTypeInfo> selectTerminalTradeTypeInfos(Integer terminalId);
}