package com.comdosoft.financial.manage.mapper.trades;

import com.comdosoft.financial.manage.domain.trades.GoodProfit;
import java.util.List;

public interface GoodProfitMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_profits
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_profits
	 * @mbggenerated
	 */
	int insert(GoodProfit record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_profits
	 * @mbggenerated
	 */
	GoodProfit selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_profits
	 * @mbggenerated
	 */
	List<GoodProfit> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table good_profits
	 * @mbggenerated
	 */
	int updateByPrimaryKey(GoodProfit record);
}