package com.comdosoft.financial.manage.mapper.trades;

import com.comdosoft.financial.manage.domain.trades.TradeTotalDayReport;
import java.util.List;

public interface TradeTotalDayReportMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_total_day_reports
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_total_day_reports
	 * @mbggenerated
	 */
	int insert(TradeTotalDayReport record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_total_day_reports
	 * @mbggenerated
	 */
	TradeTotalDayReport selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_total_day_reports
	 * @mbggenerated
	 */
	List<TradeTotalDayReport> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_total_day_reports
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TradeTotalDayReport record);
}