package com.comdosoft.financial.manage.mapper.trades;

import com.comdosoft.financial.manage.domain.trades.TradeRecord;
import com.comdosoft.financial.manage.utils.page.PageRequest;
import org.apache.ibatis.annotations.Param;

import java.util.Date;
import java.util.List;
import java.util.Map;

public interface TradeRecordMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	int insert(TradeRecord record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	TradeRecord selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	List<TradeRecord> selectAll();

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table trade_records
	 * @mbggenerated
	 */
	int updateByPrimaryKey(TradeRecord record);

	List<TradeRecord> selectPage(@Param("request") PageRequest request,
                                 @Param("start") Date start,
                                 @Param("end") Date end,
                                 @Param("type") Integer type,
                                 @Param("status") Integer status);

    long countPage(@Param("start") Date start,
                   @Param("end") Date end,
                   @Param("type") Integer type,
                   @Param("status") Integer status);

    Map<String,Long> selectPageProfit(@Param("start") Date start,
                                      @Param("end") Date end,
                                      @Param("type") Integer type,
                                      @Param("status") Integer status);
}